---
deployment:
  targets:
    - name: smmnepal
      label: SMM Nepal Production
      description: Deploy SMM Nepal panel to production
      paths:
        publish:
          - /home/username/public_html
      
      pre_deployment:
        - test -f .env || cp .env.example .env
        - mkdir -p storage/logs
        - mkdir -p storage/cache
        - mkdir -p storage/sessions
        - mkdir -p public/uploads
        - mkdir -p public/cache
        - chmod -R 755 storage public
      
      build:
        - if command -v composer >/dev/null 2>&1; then composer install --no-dev --optimize-autoloader; fi
      
      post_deployment:
        - chmod 600 .env || true
        - chmod -R 755 storage public || true
      
      exclude:
        - .git
        - .gitignore
        - node_modules
        - .env.example
        - composer.lock
        - package-lock.json
        - .cpanel.yml
        - README.md
        - DEPLOYMENT.md
        - tests
        - .editorconfig
        - .eslintrc
